name: linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [18.20.6]

    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-versions }}
        uses: actions/setup-node@v3
        with:
          node-versions: ${{ matrix.node-versions }}
          cache: 'npm'
      - name: install modules
        run: npm ci

      - name: linting typescript
        run: npm run lint:ts
      - name: linting css
        run: npm run lint:scss
      - name: unit testing
        run: npm run test:unit
      - name: build project
        run: npm run build:prod
